calendarApp/mycalendar/urls.py
from django.conf.urls import url
from django.contrib import admin
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    url(r'', include(tf_urls)),
    url(r'^admin/', admin.site.urls),
]

calendarApp/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views
from calendarApp import views
from django.contrib.auth import views as auth_views

app_name = 'calendarApp'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('register', views.RegisterView, name='register'),
    # The following path was retrieved from:
    #https://stackoverflow.com/questions/4870619/django-after-login-redirect-user-to-his-custom-page-mysite-com-username
    path('account/login/', auth_views.LoginView.as_view),
    path('templates/two_factor/core/login/', auth_views.LoginView.as_view(
        template_name='login.html',
        extra_context={
            'next': '/templates/calendarApp/index.html',
        },
    ), name='login'),

    path('templates/registration/logout.html', views.LogoutView, name='logout'),
    path('index.html', views.IndexView.as_view(), name='index'),
    url(r'^message', views.MessageView.as_view(), name='message'),
    url(r'^calendar', views.event, name='calendar'),
    path('eventNew', views.addEventView, name='new_event'),
    path('event', views.eventView, name='event_view'),
    url(r'^profile', views.ProfileView.as_view(), name='profile'),
]

mysite/urls.py
from django.conf.urls import url
from django.contrib import admin

from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from django.urls import include, path
from two_factor.urls import urlpatterns as tf_urls


urlpatterns = [
    path(r'', include(tf_urls)),
    path('admin/', admin.site.urls),
    path('webdesignproject/', include('django.contrib.auth.urls')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    path('calendarApp/', include('calendarApp.urls')),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    path('', include('calendarApp.urls')),
]

calendarApp/models.py
import datetime

from django.conf import settings
from django.db import models
from django.utils import timezone

# needed for custom user profile fields
# retrieved from https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Events(models.Model):
    start = models.DateTimeField(default=timezone.now)
    end = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title

    def create(cls, start, end, title, description):
        newEvent = cls(start=start, end=end, title=title, description=description)
        return newEvent


class Message(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  #message sender
    text = models.TextField()           #long text without a limit
    sent = models.DateTimeField(default=timezone.now)  #message sent time

    def publish(self):
        self.sent = timezone.now()
        self.save()

    def __str__(self):
        return self.text


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

calendarApp/forms.py
from django import forms
from .models import Events
from django.contrib.auth.models import User

class AddEventForm(forms.ModelForm):
    class Meta:
        model = Events
        fields = ('title', 'start', 'end', 'description')

class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

calendarApp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django import forms

from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User


from .models import Choice, Question, Events

from django.utils import timezone

from .forms import AddEventForm, RegisterForm


def eventView(request):
    eventId = request.GET.get('eventId')

    if eventId is None:
        return 404
    else:
        event = Events.objects.get(pk=eventId)
        return render(request, 'calendarApp/viewEvent.html', {
            'event': event,
        })

def event(request):
    all_events = Events.objects.all()
    # if filters applied then get parameter and filter based on condition else return object
    if request.GET:
        event_arr = []

        for i in all_events:
            event_sub_arr = {}
            event_sub_arr['title'] = i.title
            start_date = datetime.datetime.strptime(str(i.start.date()), "%Y-%m-%d").strftime("%Y-%m-%d")
            end_date = datetime.datetime.strptime(str(i.end.date()), "%Y-%m-%d").strftime("%Y-%m-%d")
            event_sub_arr['start'] = start_date
            event_sub_arr['end'] = end_date
            event_arr.append(event_sub_arr)
        return HttpResponse(json.dumps(event_arr))

    context = {
        "events":all_events,

    }
    return render(request,'calendarApp/calendar.html',context)

class HomeView(generic.ListView):
    template_name = 'calendarApp/home.html'

    def get_queryset(self):
      """Return the last five published questions."""
      return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

def LogoutView(request):
    logout(request)
    return render(request = request,
                  template_name = "calendarApp/home.html",)

class MessageView(generic.ListView):
    template_name = 'calendarApp/message.html'

    def get_queryset(self):
      """Return the last five published questions."""
      return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class IndexView(generic.ListView):
    template_name = 'calendarApp/index.html'

    def get_queryset(self):
      """Return the last five published questions."""
      return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

def addEventView(request):
     if request.method == "POST":
        form = AddEventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.save()
            return redirect('/', pk=event.pk)
     else:
        form = AddEventForm()
     return render(request, 'calendarApp/addEvent.html', {'form': form})

class ProfileView(generic.ListView):
    template_name = 'calendarApp/profile.html'

    def get_queryset(self):
      """Return the last five published questions."""
      return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

def RegisterView(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user=User.objects.create_user(form.cleaned_data['username'], password=form.cleaned_data['password'])
            user.is_superuser=False
            user.is_staff=False
            user.save()
            return redirect('/login')
    else:
        form = RegisterForm()
    return render(request, 'calendarApp/register.html', {'form': form})

calendarApp/templates/calendarApp/000.html
<!--
    Home page.
-->

{% extends 'calendarApp/base.html' %}

{% block content %}
			<div style="padding-top: 2%;">
					<p> Test content.</p>
					<a href="/logout">Logout</a>
			</div>


{% endblock %}

{% block modal %}
	{% include "modal.html" %}
{% endblock %}

calendarApp/templates/calendarApp/addEvent.html
{% extends 'calendarApp/base.html' %}

{% block content %}
  <div style="padding-left: 30%">
    <h2>New event</h2>
    <form method="POST" class="post-form" action=>{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
  </div>
{% endblock %}

calendarApp/templates/calendarApp/base.html
<!DOCTYPE HTML>
{% load static %}


<html>

<head>
	<title>Home</title>
	<meta charset="utf-8" />
	<!--Bootstrap-->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="stylesheet" href="/static/fullcalendar/fullcalendar.css"/>
	<link rel="stylesheet" href="/static/fullcalendar/fullcalendar.print.css" media="print"/>
	<!--Custom stylesheet-->
	<link rel="stylesheet" href="/static/calendarApp/resize.css" />
	<link rel="stylesheet" href="/static/calendarApp/stylesheet.css" />
</head>

<!--Header-->
<div id="header">
	<div class="top">
		<div id="info">
			<h1 style="font-size: 30px; padding-top: 15px; padding-right: 15px; color: white;">
				{% if not user.is_authenticated %}
				You are not logged in.
				{% else %}{{ user.username }}
				{% endif %}</h1>
		</div>
		<br>
<!-- Navigation for regular screen sizes -->
		<nav id="nav">
			<ul>
				<li><a href="{% url 'calendarApp:calendar' %}">Calendars</a></li>
				<li><a href="{% url 'calendarApp:new_event' %}">Add Event</a></li>
			  <li><a href="{% url 'two_factor:profile' %}"> Account Security</a></li>
				<li><a href="{% url 'calendarApp:logout' %}">Log out</a></li>
			</ul>
		</nav>

	</div>
</div>

<!--Navigation for smaller screens-->
<div id="navModal">
	<!-- Button trigger modal -->
	<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#navMenu">
		Nav
	</button>

	<!-- Modal -->
	<div class="modal fade" id="navMenu" tabindex="-1" role="dialog" aria-labelledby="navModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="navModalLabel">Menu</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<ul>
						<li><a href="{% url 'calendarApp:calendar' %}">Calendars</a></li>
						<li><a href="{% url 'calendarApp:message' %}">Messages</a></li>
					</ul>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>
</div>


<body class="is-preload">

	<div class="container" style="padding-left: 10%">

		{% block content %}{% endblock %}

	</div>

	<!-- Scripts -->
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>

	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


 <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
	<script src="/static/fullcalendar/fullcalendar.min.js"></script>
	<script>

$(document).ready(function() {

	$('#calendar').fullCalendar({
		header: {
			left: 'prev,next today',
			center: 'title',
			right: 'listDay,listWeek,month'
		},

		// customize the button names,
		// otherwise they'd all just say "list"
		views: {
			listDay: { buttonText: 'list day' },
			listWeek: { buttonText: 'list week' }
		},

		defaultView: 'month',
		navLinks: true, // can click day/week names to navigate views
		editable: true,
		eventLimit: true, // allow "more" link when too many events
		events: [
							 {% for i in events %}
							 {
									 title: "{{ i.title}}",
									 start: '{{ i.start|date:"Y-m-d" }}',
									 end: '{{ i.end|date:"Y-m-d" }}',
									 url: '/event?eventId={{i.id}}',
									 backgroundColor: '#eeeeee',
									 textColor: '#000000'

							 },
							 {% endfor %}

					 ]

});
});

</script>

</body>

</html>

calendarApp/templates/calendarApp/baseMinimal.html
<!DOCTYPE HTML>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!--Custom CSS-->
  <link rel="stylesheet" href="/static/calendarApp/stylesheet.css" />
  <title>Welcome</title>
</head>

<body class="text-center" style="background-color: #222629">

  {% block content %}{% endblock %}
  <!-- Scripts for Bootstrap -->

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

calendarApp/templates/calendarApp/home.html
<!--
    Landing page. Prompts user to log in if not already authenitcated,
    else it prompts them to go the home page.
-->

{% extends 'calendarApp/baseMinimal.html' %}

{% block title %}Home{% endblock %}

{% block content %}

{% if not user.is_authenticated %}
<h1 style="padding-bottom: 40px; padding-top:40px; font-size: 48px;">
  <b style="color: rgb(215,215,215);">You are not logged in.</b>
</h1>
<h3>
  <b style="color: rgb(215,215,215);">Please log in to continue.</b>
</h3><br>
<p><a href="/login/">Log in</a></p>
<p style="padding-top: 25px;"> Not a member?
  <br> <a href="/register">Register</a></p>

{% endif %}

{% if user.is_authenticated %}
<h1 style="padding-bottom: 40px; padding-top:40px; font-size: 48px;">
  <b style="color: rgb(215,215,215);">Welcome, {{ user.username }}</b>
</h1>
<h3>
  <b style="color: rgb(215,215,215);">Continue below</b>
</h3><br>
<p><a href="/index.html">Continue</a></p>
{% endif %}

{% endblock %}

calendarApp/templates/calendarApp/index.html
<!--
    Home page.
-->

{% extends 'calendarApp/base.html' %}

{% block content %}
  <div class="container" >
			<div style=padding-top: 2%;">
					<div  id='calendar' class="fc fc-unthemed fc-ltr"></div>
      <p><a href="{% url 'calendarApp:new_event' %}">Add event</a></p>
      </div>

  </div>
{% endblock %}

{% block modal %}
	{% include "modal.html" %}
{% endblock %}

calendarApp/templates/calendarApp/login.html
<!--
    Login form
-->

<!DOCTYPE HTML>
{% load static %}
<html lang="en">

    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <!--Custom CSS-->
      <link rel="stylesheet" href="resize.css" />
      <link rel="stylesheet" href="stylesheet.css" />
      <title>Login</title>
    </head>

    <body class="text-center" style="background-color: #222629">

      <!--Login Form-->
      <!--Reference: https://getbootstrap.com/docs/4.0/components/forms/-->
      <div class="container" style="width: 400px">
          <form class="form-signin">
            <h1 style="padding-bottom: 40px; padding-top:40px; font-size: 48px;">
              <b style="color: rgb(215,215,215);">Log In</b>
            </h1>
            <!--Username-->

            <input type="username" id="inputUsername" class="form-control" placeholder="Username" required="" autofocus="">
            <!--Password-->
            <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
            <!--Sign in-->
            <button class="btn btn-lg btn-block" type="submit" style="margin-top: 40px">Sign in</button>
          </form>
        <p style="padding-top: 25px; color: rgb(215,215,215)"> Not a member?
          <br> <a href="/register">Register</a></p>

      </div>

      <!-- Scripts for Bootstrap -->

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>

</html>

calendarApp/templates/calendarApp/register.html
<!--
    Registration.
-->
{% extends 'calendarApp/baseMinimal.html' %}
<!DOCTYPE HTML>
{% load static %}

          {% block content %}

          <h1 style="padding-bottom: 40px; padding-top:40px; font-size: 48px;">
            <b style="color: rgb(215,215,215);">Sign Up</b>
          </h1>

          <form method="POST">
              {% csrf_token %}
              {{form}}
              <br>
                <button class="btn btn-lg" type="submit" style="display: inline-block; margin-top: 40px; width: 30%">Register</button>
          </form>

          If you already have an account <a href="/login" target="blank"><strong>login</strong></a> instead.

          {% endblock %}

calendarApp/templates/calendarApp/viewEvent.html
{% extends 'calendarApp/base.html' %}

{% block content %}
<div >
  <h2> View event for {{ event.start }} </h2>
  <br>
  <p><b>Event title:</b> {{ event.title }} </p>
  <p><b>Start time:</b> {{ event.start }}  </p>
  <p><b>End time:</b> {{ event.end }}  </p>
  <p><b>Event description:</b> {{ event.description }}  </p>
  <a href="/calendar">
    <h3>&larr; Back to calendar</h3>
  </a>
</div>
{% endblock %}